rk-binary-native: Fix get_srcrev error
Add SRCREV_FORMAT to fix this error:
bb.data_smart.ExpansionError: Failure expanding variable SRCPV, expression was ${@bb.fetch2.get_srcrev(d)} which triggered exception FetchError: Fetcher failure: The SRCREV_FORMAT variable must be set when multiple SCMs are used.
The SCMs are:
git://github.com/rockchip-linux/rkbin.git;branch=master;name=rkbin
git://github.com/rockchip-linux/tools.git;branch=master;name=tools;destsuffix=git/extra

Signed-off-by: Jeffy Chen <jeffy.chen@rock-chips.com>